// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSkRfIxH5yMAMSl5NpnivtIVONdy9Qxg',
    appId: '1:758548726510:web:054f41cf9c455881d1e9ff',
    messagingSenderId: '758548726510',
    projectId: 'food-app-fe8ef',
    authDomain: 'food-app-fe8ef.firebaseapp.com',
    storageBucket: 'food-app-fe8ef.firebasestorage.app',
    databaseURL: 'https://food-app-fe8ef-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRcMrMAjS1CeCNVaMwR_1s8iMpdOpoog',
    appId: '1:758548726510:android:855e6bbf5a3839cbd1e9ff',
    messagingSenderId: '758548726510',
    projectId: 'food-app-fe8ef',
    storageBucket: 'food-app-fe8ef.firebasestorage.app',
    databaseURL: 'https://food-app-fe8ef-default-rtdb.firebaseio.com/',
  );
}
